### ISSUE TITLE
How to use follow.py ?

### ISSUE THREAD

**Issue by Grices** [IvLabs/person_following_bot#9]
Hi, I've built the software environment on Jetson TX2 as you asked, how do I run the follow.py next? I have try `rosrun follow.py` but  it didn't work. Could you give me a program guide？
Thanks.

**Comment by take2rohit** [comment]
Since its a python file you need to run by typing `python3 follow.py`. I suppose the code was meant to be run on python3.6.

**Comment by Grices** [comment]
> 
> 
> Since its a python file you need to run by typing `python3 follow.py`. I suppose the code was meant to be run on python3.6.

Thank you very much for your answers, I will try to run, I will consult you again if there are other questions.

**Comment by Grices** [comment]
Hi, when I run `pyrhon3 follow.py`, there is such an error 
`Traceback (most recent call last):
  File "follow.py", line 16, in <module>
    from realsense import *
  File "/home/nvidia/person_following_bot/realsense.py", line 14, in <module>
    import pandas as pd
  File "/usr/lib/python3/dist-packages/pandas/__init__.py", line 58, in <module>
    from pandas.io.api import *
  File "/usr/lib/python3/dist-packages/pandas/io/api.py", line 19, in <module>
    from pandas.io.packers import read_msgpack, to_msgpack
  File "/usr/lib/python3/dist-packages/pandas/io/packers.py", line 68, in <module>
    from pandas.util._move import (
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 0: invalid start byte`.
How should I solve this problem? 
Thanks, Sir.

**Comment by Grices** [comment]
> Since its a python file you need to run by typing `python3 follow.py`. I suppose the code was meant to be run on python3.6.

Hi, when I run pyrhon3 follow.py, there is such an error
Traceback (most recent call last): File "follow.py", line 16, in <module> from realsense import * File "/home/nvidia/person_following_bot/realsense.py", line 14, in <module> import pandas as pd File "/usr/lib/python3/dist-packages/pandas/__init__.py", line 58, in <module> from pandas.io.api import * File "/usr/lib/python3/dist-packages/pandas/io/api.py", line 19, in <module> from pandas.io.packers import read_msgpack, to_msgpack File "/usr/lib/python3/dist-packages/pandas/io/packers.py", line 68, in <module> from pandas.util._move import ( UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 0: invalid start byte.
How should I solve this problem?
Thanks, Sir.

**Comment by take2rohit** [comment]
I don't know we didn't face such error. But it seems that there is some non ascii character in dictionary. You may refer stackoverflow for solution..

https://stackoverflow.com/questions/22216076/unicodedecodeerror-utf8-codec-cant-decode-byte-0xa5-in-position-0-invalid-s
